dist: xenial
language: c
os:
  - linux
  - osx
#compiler:
#  - gcc
#  - clang
cache:
  pip: true
services:
- docker
before_install:
  - OS=linux
  - ARCH=x86_64
  - V=3.7.1
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then OS=darwin; fi
  - GH_BASE="https://github.com/bazelbuild/bazel/releases/download/$V"
  - GH_ARTIFACT="bazel-$V-installer-$OS-$ARCH.sh"
  - URL="$GH_BASE/$GH_ARTIFACT"
  - echo $URL
  - wget -O install.sh $URL
  - chmod +x install.sh
  - ./install.sh --user
  - rm -f install.sh
script:
  - bazel --version

